<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

 class  Etablissement extends Model
{
    /**
     * Primary key type.
     *
     * @var string
     */
    //public  $table="etblissements";
    protected $keyType = 'bigInteger';

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'nom' => 'string',
        'type_etablissement_id' => 'integer',
        'categerie_etablissement_id' => 'integer',
        'classe' => 'boolean',
        'sous_type_id' => 'integer',
        'etblissement_id' => 'integer',
        'forchette_id' => 'integer'
    ];

    public function typeEtablissement()
    {
        return $this->belongsTo(TypeEtablissement::class, 'type_id', 'id');
    }

    public function categerieEtablissement()
    {
        return $this->belongsTo('\App\Models\Categerie_etablissement', 'categerie_etablissement_id', 'id');
    }

    public function sousType()
    {
        return $this->belongsTo('\App\Models\SousType', 'sous_type_id', 'id');
    }

public function fichenuitees(){

    return $this->hasManyThrough(FicheNuitee::class,FicheHebergement::class);
}




public function fichenuiteesreto(){

    return $this->hasManyThrough(FicheNuiteeRestauration::class,FicheHebergement::class);
}    




    public function forchette()
    {
        return $this->belongsTo('\App\Models\Forchette', 'forchette_id', 'id');
    }



    public function ficheHebergements()
    {
        return $this->hasMany(FicheHebergement::class, 'etablissement_id', 'id');
    }

    public function ficheRestaurations()
    {
        return $this->hasMany(FicheRestauration::class, 'etablissement_id', 'id');
    }

    public function users()
    {
        return $this->hasMany(User::class);
    }
}
