<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\Models;

use Illuminate\Database\Eloquent\Model;

  class TypeEtablissement  extends Model
{
    /**  
     * Primary key type.
     * 
     * @var string
     */
    public $table="types";
    protected $keyType = 'bigInteger';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'nom' => 'string'
    ];
    
    public function etablissements()
    {
        return $this->hasMany('\App\Models\Etablissement', 'type_etablissement_id', 'id');
    }
    
    public function sousTypes()
    {
        return $this->hasOne('\App\Models\SousType', 'type_etablissement_id', 'id');
    }
}
